### ISSUE TITLE
Handles loops to request more data

### ISSUE THREAD

**Issue by mkellerman** [mkellerman/PSTwitterAPI#13]
Example:
`Get-TwitterUsers_Lookup`

There is a max number of IDs you can provide per call.

**Comment by mkellerman** [comment]
Some of this implementation is already done.

This is why you would set more than one OAuthSettings. When doing a Get-TwitterOAuthSettings, it sorts by the one that has more rate limit available.

This implementation should be reviewed, and see if there is a better way of doing it.

**Comment by ConstantineK** [comment]
Ahh that makes sense, I saw the token stuff but didnt suss it out right away.

**Comment by mkellerman** [comment]
Wrong PR
