### ISSUE TITLE
Suggesting Link Change in README.md  - "Resources"

### ISSUE THREAD

**Issue by ctmcisco** [mkellerman/PSTwitterAPI#22]
This link is no longer available:
https://twittercommunity.com/t/how-to-get-my-api-key/7033 <--- NO BUENO

That whole process has changed, you now need to register as a developer https://developer.twitter.com/en/apply-for-access and create an app in there https://developer.twitter.com/en/apps/create to get keys

The above explanation is comes from the link below:
https://twittercommunity.com/t/twitter-oauth-keys/119836

**Comment by mkellerman** [comment]
#23 

Nice work on your first PR! Thanks for your contribution! 👍
