### ISSUE TITLE
Azure pipelines OAuth script variable

### ISSUE THREAD

**Issue by whiteken** [mkellerman/PSTwitterAPI#32]
Hi

I hit an issue when using the module in Azure DevOps pipelines
I forked the repo and did a (quite a horrible) workaround here:

https://github.com/whiteken/NSTrainTime/tree/master/PSTwitterAPI/0.0.7

Due to scoping on the build agent it wasn't able to find the script variable for Oauth settings so I dump it out to clixml instead.

Could a condition to chose this for AZDO be included in the update?

**Comment by mkellerman** [comment]
It’s currently using environment variables if they exists. 

If you would like any alternative solutions, please make a PR for me to evaluate officially.
