### ISSUE TITLE
Azure pipelines Install module -Force

### ISSUE THREAD

**Issue by whiteken** [mkellerman/PSTwitterAPI#33]
When installing the current version during Azure Pipelines release, it's necessary to use the -Force parameter:

Install-PackageProvider -Name PSTwitterAPI -Force -Scope CurrentUser

The build server is stateless so the module hasn't been installed before.  
In this case, -Force along with no previous module installation, results in the error:
During module import on Exporting function Set-TwitterOAuthSettings

"No OAuthSettings was found. Use 'Set-TwitterOAuthSettings' to set PSTwitterAPI ApiKey & Token."

Could you remove the throw on the next update so that it's possible to use the PS Gallery version again?

https://github.com/whiteken/NSTrainTime/blob/master/PSTwitterAPI/0.0.7/public/Get-TwitterOAuthSettings.ps1

Otherwise the module is fantastic... saved me a tonne of time - thanks :)

**Comment by mkellerman** [comment]
Please make the appropriate PR changes and I’ll merge in.

**Comment by whiteken** [comment]
Great - will do thanks!

**Comment by mkellerman** [comment]
#35 resolved
