### ISSUE TITLE
Secret Access Token not accepted

### ISSUE THREAD

**Issue by Skyyblaze** [mkellerman/PSTwitterAPI#36]
I might be doing something wrong as the tutorial sadly isn't very detailed but I'm getting an error trying to set up PSTwitterAPI. I installed it just fine and then edited my PowerShell startup script by adding:

```
Import-Module PSTwitterAPI

$OAuthSettings = @{
  "MYAPIKEY" = $env:ApiKey
  "MYAPISECRET" = $env:ApiSecret
  "MYACCESSTOKEN" = $env:AccessToken
  "MYACCESSTOKENSECRET" =$env:AccessTokenSecret
}
Set-TwitterOAuthSettings @OAuthSettings
```

The first three keys seem to check out but the last one returns an error akin to "Invalid value for AccessTokenSecret, no value was assigned". I had to paraphrase as my Windows is set to German. Did I add the keys wrong? I'm new to PowerShell.

EDIT: I thought I would add the exact error message in German:
`
Set-TwitterOAuthSettings : Es wurde kein Parameter gefunden, der dem Parameternamen "MYACCESSTOKENSECRET" entspricht.`

A better translation would be:

There is no parameter that matches the parameter-name "MYACCESSTOKENSECRET". It shows the actual token there to clarify but of course I won't post that online.

**Comment by mkellerman** [comment]
Sorry for the lack of feedback. Has your problem been resolved?

You should maybe set $OAuthSettings 'BEFORE' your import the module.
