### ISSUE TITLE
running Set-TwitterOAuthSettings in script

### ISSUE THREAD

**Issue by veepee78** [mkellerman/PSTwitterAPI#37]
I have this in script:
$ErrorActionPreference = 'Continue'

try {
  Import-Module PSTwitterAPI
  Set-TwitterOAuthSettings -ApiKey 'xx' -ApiSecret 'xx' -AccessToken 'xx' -AccessTokenSecret 'xx'
...

this causes error:
No OAuthSettings was found. Use 'Set-TwitterOAuthSettings' to set PSTwitterAPI ApiKey & Token.
At C:\Program Files\WindowsPowerShell\Modules\PSTwitterAPI\0.0.7\public\Get-TwitterOAuthSettings.ps1:35 char:9
+         Throw "No OAuthSettings was found. Use 'Set-TwitterOAuthSetti ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No OAuthSetting...ApiKey & Token.:String) [], RuntimeException
    + FullyQualifiedErrorId : No OAuthSettings was found. Use 'Set-TwitterOAuthSettings' to set PSTwitterAPI ApiKey & Token.

looks like erroraction part in Set-TwitterOAuthSettings in script is being ignored.
...
If ($OAuthSettings = Get-TwitterOAuthSettings -AccessToken $AccessToken -ErrorAction SilentlyContinue) 
...

If I remove throw from Get-TwitterOAuthSettings, it works.

Set-TwitterOAuthSettings works when run on command line..?

**Comment by veepee78** [comment]
Haven't tried other versions, this happens on powershell 5.1.

**Comment by mkellerman** [comment]
This was resolved with #35
