### ISSUE TITLE
Project School

### ISSUE THREAD

**Issue by ToonStaes** [mkellerman/PSTwitterAPI#39]
For a project at school I'll be using this API which will make my life a lot easier. Whilst setting up the API I came across a Problem. I am a rookie if it comes to PowerShell so this is probably an easy fix but I can't seem to find it. When I want to import the module I get the error that it cannot be loaded because running scripts is disabled on this system.

Can someone tell me what i need to do exactly?

![image](https://user-images.githubusercontent.com/57673222/79977663-ee8ae280-849e-11ea-8c90-bbfecf0be436.png)

In addition to the project, can someone tell me how i can search for tweets using a specific hashtag?

Thank you in advance
Toon Staes

**Comment by mkellerman** [comment]
Please look at: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy

Closing this Issue as this is not an issue with the module.

PS: for more general help about powershell and how to install/run modules, join us on Discord https://aka.ms/psdiscord
