### ISSUE TITLE
Get-TwitterStatuses_UserTimeline not displaying full_text

### ISSUE THREAD

**Issue by spodg13** [mkellerman/PSTwitterAPI#49]
I believe there is a parameter tweet_extended which can be set to yes/no but I am not sure how to pull and fix that.  It might also be a matter of requesting full_text vs text according to what I have read.  Is it simply a matter of updating the API JSON file?

**Comment by spodg13** [comment]
I believe there is a parameter tweet_extended which can be set to yes/no but I am not sure how to pull and fix that

**Comment by mkellerman** [comment]
Working on a fix. Might need you to pull a branch and test for me please. Will advise when ready.

**Comment by mkellerman** [comment]
Please pull this branch, and test. Let me know if this fixes this issue. 

You'll need to use the parameter `-tweet_mode extended`

**Comment by spodg13** [comment]
I appreciate this module, and your fast response.  Between how my company has things locked down and being somewhat new at github, best I could do was copy the changes into my module location, 4 files as noted.  I don't get the auto-populate for the parameter like I do with the other parameters.  I used -tweet_mode extended and received an error: 
 Get-TwitterStatuses_UserTimeline : A parameter cannot be found that matches parameter name 'tweet_mode'.
At line:1 char:67
+ ... itterStatuses_UserTimeline -screen_name 'spodg13' -tweet_mode 'extend ...
I will try to re-install the module.  Thanks so much for your efforts

**Comment by spodg13** [comment]
Re-imported the module.  parameters came up.  used -tweet_mode extended , no quotes on extended and it worked like a charm!!  Thanks again, sorry I was not able to pull, but I can confirm the fix worked and can be merged

**Comment by mkellerman** [comment]
Thanks for testing!
